package controler;
// Generated 23/09/2017 20:31:46 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer id;
     private String nomeFantasia;
     private String razaoSocial;
     private String inscricaoEstad;
     private String cnpj;
     private String telefone;
     private String email;
     private String cep;
     private String rua;
     private String bairro;
     private int numeroCasa;
     private String uf;
     private String cidade;
     private String parceiro;

    public Fornecedor() {
    }

    public String[] getFornecedor(){
             return new String[]{
                          String.valueOf(id),
                          nomeFantasia,
                          razaoSocial,
                          inscricaoEstad,
                          cnpj,
                          telefone,
                          email,
                          cep,
                          rua,
                          bairro,
                          String.valueOf(numeroCasa),
                          uf,
                          cidade,
                          parceiro
             };
}
    
    public Fornecedor(String nomeFantasia, String razaoSocial, String inscricaoEstad, String cnpj, String telefone, String email, String cep, String rua, String bairro, int numeroCasa, String uf, String cidade, String parceiro) {
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.inscricaoEstad = inscricaoEstad;
       this.cnpj = cnpj;
       this.telefone = telefone;
       this.email = email;
       this.cep = cep;
       this.rua = rua;
       this.bairro = bairro;
       this.numeroCasa = numeroCasa;
       this.uf = uf;
       this.cidade = cidade;
       this.parceiro = parceiro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getInscricaoEstad() {
        return this.inscricaoEstad;
    }
    
    public void setInscricaoEstad(String inscricaoEstad) {
        this.inscricaoEstad = inscricaoEstad;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public int getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(int numeroCasa) {
        this.numeroCasa = numeroCasa;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getParceiro() {
        return this.parceiro;
    }
    
    public void setParceiro(String parceiro) {
        this.parceiro = parceiro;
    }




}


