package controler;
// Generated 23/09/2017 20:31:46 by Hibernate Tools 4.3.1

import java.util.List;




/**
 * UsuarioSistema generated by hbm2java
 */
public class UsuarioSistema  implements java.io.Serializable {


     private Integer id;
     private String nomeUser;
     private String login;
     private String senha;

    public UsuarioSistema() {
    }
    
    public String[] getUsuarioSistema(){
             return new String[]{
                          String.valueOf(id),
                          nomeUser,
                          login,
                          senha
             };
}
    
    public String BuscaSenhaELogin(String login, char[] senha) {
        String VerificacaoLogin = "FROM usuarioSistema WHERE login like '" + login + "' and senha like'" + senha + "'";
                 if (VerificacaoLogin.) {
                              
                 }
        return VerificacaoLogin;
    }

    public UsuarioSistema(String nomeUser, String login, String senha) {
       this.nomeUser = nomeUser;
       this.login = login;
       this.senha = senha;
    }
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeUser() {
        return this.nomeUser;
    }
    
    public void setNomeUser(String nomeUser) {
        this.nomeUser = nomeUser;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


