/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author tiago
 */
public class FormUsuario extends javax.swing.JFrame {

             /**
              * Creates new form FormUsuario
              */
             public FormUsuario() {
                          initComponents();
             }

             /**
              * This method is called from within the constructor to initialize
              * the form. WARNING: Do NOT modify this code. The content of this
              * method is always regenerated by the Form Editor.
              */
             @SuppressWarnings("unchecked")
             // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
             private void initComponents() {

                          jButton1 = new javax.swing.JButton();
                          jButton2 = new javax.swing.JButton();
                          jPanel1 = new javax.swing.JPanel();
                          jLabel1 = new javax.swing.JLabel();
                          txtNomeUsuario = new javax.swing.JTextField();
                          jLabel2 = new javax.swing.JLabel();
                          txtLogin = new javax.swing.JTextField();
                          jLabel3 = new javax.swing.JLabel();
                          txtSenha = new javax.swing.JPasswordField();

                          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                          jButton1.setText("Cadastrar");

                          jButton2.setText("Sair");

                          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar novo usuario"));

                          jLabel1.setText("Nome do usuario:");

                          jLabel2.setText("Login:");

                          jLabel3.setText("Senha:");

                          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                          jPanel1.setLayout(jPanel1Layout);
                          jPanel1Layout.setHorizontalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addComponent(txtNomeUsuario)
                                                                 .addComponent(txtLogin)
                                                                 .addComponent(txtSenha)
                                                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                                                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addComponent(jLabel2)
                                                                                           .addComponent(jLabel3)
                                                                                           .addComponent(jLabel1))
                                                                              .addGap(0, 0, Short.MAX_VALUE)))
                                                    .addContainerGap())
                          );
                          jPanel1Layout.setVerticalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                          );

                          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                          getContentPane().setLayout(layout);
                          layout.setHorizontalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addContainerGap())
                                       .addGroup(layout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(jButton1)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(jButton2)
                                                    .addContainerGap(52, Short.MAX_VALUE))
                          );
                          layout.setVerticalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jButton1)
                                                                 .addComponent(jButton2))
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                          );

                          pack();
             }// </editor-fold>//GEN-END:initComponents

             

             // Variables declaration - do not modify//GEN-BEGIN:variables
             private javax.swing.JButton jButton1;
             private javax.swing.JButton jButton2;
             private javax.swing.JLabel jLabel1;
             private javax.swing.JLabel jLabel2;
             private javax.swing.JLabel jLabel3;
             private javax.swing.JPanel jPanel1;
             private javax.swing.JTextField txtLogin;
             private javax.swing.JTextField txtNomeUsuario;
             private javax.swing.JPasswordField txtSenha;
             // End of variables declaration//GEN-END:variables
}
