/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOSistema;
import controler.Cliente;
import controler.Fornecedor;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author tiago
 */
public class FormMDI extends javax.swing.JFrame {

             private DefaultTableModel dtm;
             private int id;
             
             /**
              * Creates new form FormMDI
              */
             public FormMDI() {
                          initComponents();
                          dtm = (DefaultTableModel)tblFornecedores.getModel();
                          carregarTabela(null);
                          id = -1;
             }

             /**
              * This method is called from within the constructor to initialize
              * the form. WARNING: Do NOT modify this code. The content of this
              * method is always regenerated by the Form Editor.
              */
             @SuppressWarnings("unchecked")
             // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
             private void initComponents() {

                          buttonGroup1 = new javax.swing.ButtonGroup();
                          dktPrincipal = new javax.swing.JDesktopPane();
                          jTabbedPane1 = new javax.swing.JTabbedPane();
                          jPanel1 = new javax.swing.JPanel();
                          tpnCadastro = new javax.swing.JTabbedPane();
                          jPanel6 = new javax.swing.JPanel();
                          jLabel1 = new javax.swing.JLabel();
                          txtNomeFantasia = new javax.swing.JTextField();
                          jLabel2 = new javax.swing.JLabel();
                          txtRazaoSocial = new javax.swing.JTextField();
                          jLabel3 = new javax.swing.JLabel();
                          txtCnpj = new javax.swing.JFormattedTextField();
                          jLabel4 = new javax.swing.JLabel();
                          txtTelefone = new javax.swing.JFormattedTextField();
                          jLabel5 = new javax.swing.JLabel();
                          txtEmail = new javax.swing.JTextField();
                          jLabel6 = new javax.swing.JLabel();
                          txtLogradouro = new javax.swing.JTextField();
                          jLabel7 = new javax.swing.JLabel();
                          txtBairro = new javax.swing.JTextField();
                          jLabel8 = new javax.swing.JLabel();
                          txtNumeroCasa = new javax.swing.JTextField();
                          jLabel9 = new javax.swing.JLabel();
                          cbxUf = new javax.swing.JComboBox<>();
                          jLabel10 = new javax.swing.JLabel();
                          cbxCidade = new javax.swing.JComboBox<>();
                          jLabel11 = new javax.swing.JLabel();
                          txtCep = new javax.swing.JFormattedTextField();
                          btnBuscaCep = new javax.swing.JButton();
                          jLabel12 = new javax.swing.JLabel();
                          txtInscricaoEstadual = new javax.swing.JFormattedTextField();
                          btnNovo = new javax.swing.JButton();
                          btnSalvar = new javax.swing.JButton();
                          btnCancel = new javax.swing.JButton();
                          btnEditar = new javax.swing.JButton();
                          cbxParceiro = new javax.swing.JComboBox<>();
                          jLabel13 = new javax.swing.JLabel();
                          jPanel5 = new javax.swing.JPanel();
                          btnBuscarClientes = new javax.swing.JButton();
                          jLabel16 = new javax.swing.JLabel();
                          txtBuscaClientes = new javax.swing.JTextField();
                          btnExcluirCliente = new javax.swing.JButton();
                          btnEditarCliente = new javax.swing.JButton();
                          btnCancelar = new javax.swing.JButton();
                          jScrollPane3 = new javax.swing.JScrollPane();
                          tblFornecedores = new javax.swing.JTable();
                          jLabel14 = new javax.swing.JLabel();
                          lblTotalDeClientes = new javax.swing.JLabel();
                          jPanel11 = new javax.swing.JPanel();
                          jPanel12 = new javax.swing.JPanel();
                          chbNome = new javax.swing.JCheckBox();
                          chbEndereco = new javax.swing.JCheckBox();
                          chbTelefone = new javax.swing.JCheckBox();
                          chbEmail = new javax.swing.JCheckBox();
                          chbId = new javax.swing.JCheckBox();
                          chbUsuario = new javax.swing.JCheckBox();
                          chbParceiro = new javax.swing.JCheckBox();
                          jLabel17 = new javax.swing.JLabel();
                          cbxOrdenNome = new javax.swing.JComboBox<>();
                          jScrollPane1 = new javax.swing.JScrollPane();
                          jTable2 = new javax.swing.JTable();
                          cbxMenorMaior = new javax.swing.JComboBox<>();
                          jPanel7 = new javax.swing.JPanel();
                          jTabbedPane2 = new javax.swing.JTabbedPane();
                          jPanel8 = new javax.swing.JPanel();
                          jPanel2 = new javax.swing.JPanel();
                          jPanel3 = new javax.swing.JPanel();
                          jTabbedPane3 = new javax.swing.JTabbedPane();
                          jPanel9 = new javax.swing.JPanel();
                          jPanel10 = new javax.swing.JPanel();
                          jLabel15 = new javax.swing.JLabel();
                          jTextField1 = new javax.swing.JTextField();
                          chxNome = new javax.swing.JCheckBox();
                          chxNome1 = new javax.swing.JCheckBox();
                          chxNome2 = new javax.swing.JCheckBox();
                          chxNome3 = new javax.swing.JCheckBox();
                          chxNome4 = new javax.swing.JCheckBox();
                          jButton5 = new javax.swing.JButton();
                          jScrollPane2 = new javax.swing.JScrollPane();
                          jTable1 = new javax.swing.JTable();
                          btnImprimirRelatorio = new javax.swing.JButton();
                          jButton6 = new javax.swing.JButton();
                          jPanel4 = new javax.swing.JPanel();
                          jMenuBar1 = new javax.swing.JMenuBar();
                          jMenu1 = new javax.swing.JMenu();
                          jMenu2 = new javax.swing.JMenu();
                          jMenu3 = new javax.swing.JMenu();
                          jMenuItem1 = new javax.swing.JMenuItem();
                          jMenuItem2 = new javax.swing.JMenuItem();
                          jMenuItem3 = new javax.swing.JMenuItem();
                          jMenu4 = new javax.swing.JMenu();
                          jMenuItem4 = new javax.swing.JMenuItem();
                          jMenuItem5 = new javax.swing.JMenuItem();
                          jMenu5 = new javax.swing.JMenu();

                          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                          setAlwaysOnTop(true);
                          setExtendedState(6);

                          jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

                          jLabel1.setText("Nome fantasia:");

                          jLabel2.setText("Razão Social:");

                          jLabel3.setText("CNPJ:");

                          try {
                                       txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####")));
                          } catch (java.text.ParseException ex) {
                                       ex.printStackTrace();
                          }

                          jLabel4.setText("Telefone:");

                          try {
                                       txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
                          } catch (java.text.ParseException ex) {
                                       ex.printStackTrace();
                          }

                          jLabel5.setText("E-mail:");

                          jLabel6.setText("Rua:");

                          jLabel7.setText("Bairro:");

                          jLabel8.setText("Numero:");

                          jLabel9.setText("UF:");

                          cbxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "PR" }));

                          jLabel10.setText("Cidade:");

                          cbxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                          jLabel11.setText("CEP:");

                          try {
                                       txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
                          } catch (java.text.ParseException ex) {
                                       ex.printStackTrace();
                          }

                          btnBuscaCep.setText("Busca CEP");

                          jLabel12.setText("Inscrição Estadual:");

                          try {
                                       txtInscricaoEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
                          } catch (java.text.ParseException ex) {
                                       ex.printStackTrace();
                          }

                          btnNovo.setText("Novo");

                          btnSalvar.setText("Salvar");
                          btnSalvar.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    btnSalvarActionPerformed(evt);
                                       }
                          });

                          btnCancel.setText("Cancelar");

                          btnEditar.setText("Editar");
                          btnEditar.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    btnEditarActionPerformed(evt);
                                       }
                          });

                          cbxParceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

                          jLabel13.setText("Parceiro");

                          javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                          jPanel6.setLayout(jPanel6Layout);
                          jPanel6Layout.setHorizontalGroup(
                                       jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(jPanel6Layout.createSequentialGroup()
                                                                              .addContainerGap()
                                                                              .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                           .addComponent(txtNomeFantasia)
                                                                                           .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(jLabel1)
                                                                                                                     .addComponent(jLabel2)
                                                                                                                     .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                               .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                               .addComponent(jLabel3))
                                                                                                                                  .addGap(18, 18, 18)
                                                                                                                                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                               .addComponent(jLabel4)
                                                                                                                                               .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addGap(18, 18, 18)
                                                                                                                                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                               .addComponent(txtEmail)
                                                                                                                                               .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                                            .addComponent(jLabel5)
                                                                                                                                                            .addGap(0, 0, Short.MAX_VALUE))))
                                                                                                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                  .addComponent(jLabel12)
                                                                                                                                  .addGap(39, 39, 39))))
                                                                                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(jLabel11)
                                                                                                                     .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                  .addGap(18, 18, 18)
                                                                                                                                  .addComponent(btnBuscaCep)))
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(txtLogradouro)
                                                                                                                     .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addComponent(jLabel6)
                                                                                                                                  .addGap(0, 0, Short.MAX_VALUE))))
                                                                                           .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                        .addComponent(txtRazaoSocial)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                           .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                                                                  .addComponent(jLabel7)
                                                                                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                     .addComponent(txtBairro))
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(jLabel8)
                                                                                                                     .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(cbxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                     .addComponent(jLabel9))
                                                                                                        .addGap(29, 29, 29)
                                                                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                     .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                     .addComponent(jLabel10)))))
                                                                 .addGroup(jPanel6Layout.createSequentialGroup()
                                                                              .addGap(13, 13, 13)
                                                                              .addComponent(jLabel13)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                              .addComponent(cbxParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addGap(0, 0, Short.MAX_VALUE)))
                                                    .addContainerGap())
                                       .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addGap(32, 32, 32)
                                                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addContainerGap(62, Short.MAX_VALUE))
                          );
                          jPanel6Layout.setVerticalGroup(
                                       jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel6Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jLabel2)
                                                                 .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jLabel3)
                                                                 .addComponent(jLabel4)
                                                                 .addComponent(jLabel5))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                              .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jLabel6)
                                                                 .addComponent(jLabel11))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(btnBuscaCep))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jLabel7)
                                                                 .addComponent(jLabel8)
                                                                 .addComponent(jLabel9)
                                                                 .addComponent(jLabel10))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(cbxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(28, 28, 28)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(cbxParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(jLabel13))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(btnNovo)
                                                                 .addComponent(btnSalvar)
                                                                 .addComponent(btnCancel)
                                                                 .addComponent(btnEditar))
                                                    .addContainerGap(50, Short.MAX_VALUE))
                          );

                          tpnCadastro.addTab("Cadastro", jPanel6);

                          jPanel5.setAutoscrolls(true);

                          btnBuscarClientes.setText("Buscar");
                          btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    btnBuscarClientesActionPerformed(evt);
                                       }
                          });

                          jLabel16.setText("Buscar fornecedores:");

                          btnExcluirCliente.setText("Excluir");

                          btnEditarCliente.setText("Editar");
                          btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    btnEditarClienteActionPerformed(evt);
                                       }
                          });

                          btnCancelar.setText("Cancelar");

                          tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
                                       new Object [][] {
                                                    {null, null, null, null, null, null, null},
                                                    {null, null, null, null, null, null, null},
                                                    {null, null, null, null, null, null, null},
                                                    {null, null, null, null, null, null, null}
                                       },
                                       new String [] {
                                                    "ID", "Nome Fantasia", "Razão Social", "CNPJ", "Endereço", "Telefone", "Pareceiro"
                                       }
                          ) {
                                       boolean[] canEdit = new boolean [] {
                                                    false, false, false, false, false, false, false
                                       };

                                       public boolean isCellEditable(int rowIndex, int columnIndex) {
                                                    return canEdit [columnIndex];
                                       }
                          });
                          tblFornecedores.setToolTipText("");
                          tblFornecedores.getTableHeader().setReorderingAllowed(false);
                          jScrollPane3.setViewportView(tblFornecedores);
                          if (tblFornecedores.getColumnModel().getColumnCount() > 0) {
                                       tblFornecedores.getColumnModel().getColumn(0).setPreferredWidth(5);
                                       tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(200);
                                       tblFornecedores.getColumnModel().getColumn(2).setPreferredWidth(200);
                                       tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(70);
                                       tblFornecedores.getColumnModel().getColumn(4).setPreferredWidth(100);
                                       tblFornecedores.getColumnModel().getColumn(5).setPreferredWidth(70);
                                       tblFornecedores.getColumnModel().getColumn(6).setPreferredWidth(20);
                          }

                          jLabel14.setText("Total de registros:");

                          lblTotalDeClientes.setText("0");

                          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                          jPanel5.setLayout(jPanel5Layout);
                          jPanel5Layout.setHorizontalGroup(
                                       jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(jPanel5Layout.createSequentialGroup()
                                                                              .addGap(7, 7, 7)
                                                                              .addComponent(jLabel16))
                                                                 .addGroup(jPanel5Layout.createSequentialGroup()
                                                                              .addGap(6, 6, 6)
                                                                              .addComponent(jLabel14)
                                                                              .addGap(6, 6, 6)
                                                                              .addComponent(lblTotalDeClientes)
                                                                              .addGap(404, 404, 404)
                                                                              .addComponent(btnCancelar)
                                                                              .addGap(6, 6, 6)
                                                                              .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addGap(6, 6, 6)
                                                                              .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                 .addGroup(jPanel5Layout.createSequentialGroup()
                                                                              .addGap(7, 7, 7)
                                                                              .addComponent(txtBuscaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                              .addComponent(btnBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                       .addComponent(jScrollPane3)
                          );
                          jPanel5Layout.setVerticalGroup(
                                       jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(jLabel16)
                                                    .addGap(2, 2, 2)
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(txtBuscaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(btnBuscarClientes))
                                                    .addGap(13, 13, 13)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addComponent(jLabel14)
                                                                 .addComponent(lblTotalDeClientes)
                                                                 .addComponent(btnCancelar)
                                                                 .addComponent(btnExcluirCliente)
                                                                 .addComponent(btnEditarCliente)))
                          );

                          tpnCadastro.addTab("Exibição", jPanel5);

                          jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                          jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Colunas a serem exibidas"));

                          chbNome.setSelected(true);
                          chbNome.setText("Nome");

                          chbEndereco.setSelected(true);
                          chbEndereco.setText("Endereço");

                          chbTelefone.setSelected(true);
                          chbTelefone.setText("Telefone");

                          chbEmail.setSelected(true);
                          chbEmail.setText("E-mail");

                          chbId.setSelected(true);
                          chbId.setText("Id");

                          chbUsuario.setSelected(true);
                          chbUsuario.setText("Usuario de contato");

                          chbParceiro.setSelected(true);
                          chbParceiro.setText("Parceiro");

                          javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                          jPanel12.setLayout(jPanel12Layout);
                          jPanel12Layout.setHorizontalGroup(
                                       jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel12Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(chbId)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(chbNome)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(chbEndereco)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(chbTelefone)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(chbEmail)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(chbUsuario)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(chbParceiro)
                                                    .addContainerGap())
                          );
                          jPanel12Layout.setVerticalGroup(
                                       jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel12Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(chbId)
                                                                 .addComponent(chbNome)
                                                                 .addComponent(chbEndereco)
                                                                 .addComponent(chbTelefone)
                                                                 .addComponent(chbEmail)
                                                                 .addComponent(chbUsuario)
                                                                 .addComponent(chbParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addContainerGap(16, Short.MAX_VALUE))
                          );

                          jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

                          jLabel17.setText("Ordenar por (nome):");
                          jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 86, -1, -1));

                          cbxOrdenNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A - Z", "Z- A" }));
                          jPanel11.add(cbxOrdenNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 290, -1));

                          jTable2.setModel(new javax.swing.table.DefaultTableModel(
                                       new Object [][] {
                                                    {null, null, null},
                                                    {null, null, null},
                                                    {null, null, null},
                                                    {null, null, null}
                                       },
                                       new String [] {
                                                    "Id", "Nome", "E-mail"
                                       }
                          ) {
                                       boolean[] canEdit = new boolean [] {
                                                    false, false, false
                                       };

                                       public boolean isCellEditable(int rowIndex, int columnIndex) {
                                                    return canEdit [columnIndex];
                                       }
                          });
                          jScrollPane1.setViewportView(jTable2);
                          if (jTable2.getColumnModel().getColumnCount() > 0) {
                                       jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
                                       jTable2.getColumnModel().getColumn(1).setPreferredWidth(250);
                                       jTable2.getColumnModel().getColumn(2).setPreferredWidth(300);
                          }

                          jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 675, 307));

                          cbxMenorMaior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maior - Menor", "Menor - Maior" }));
                          jPanel11.add(cbxMenorMaior, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

                          tpnCadastro.addTab("Relatorio", jPanel11);

                          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                          jPanel1.setLayout(jPanel1Layout);
                          jPanel1Layout.setHorizontalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(tpnCadastro)
                          );
                          jPanel1Layout.setVerticalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(tpnCadastro)
                          );

                          tpnCadastro.getAccessibleContext().setAccessibleName("Clientes");

                          jTabbedPane1.addTab("Clientes", jPanel1);

                          javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                          jPanel8.setLayout(jPanel8Layout);
                          jPanel8Layout.setHorizontalGroup(
                                       jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 857, Short.MAX_VALUE)
                          );
                          jPanel8Layout.setVerticalGroup(
                                       jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 448, Short.MAX_VALUE)
                          );

                          jTabbedPane2.addTab("Clientes", jPanel8);

                          javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                          jPanel7.setLayout(jPanel7Layout);
                          jPanel7Layout.setHorizontalGroup(
                                       jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane2)
                          );
                          jPanel7Layout.setVerticalGroup(
                                       jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane2)
                          );

                          jTabbedPane1.addTab("Editar", jPanel7);

                          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                          jPanel2.setLayout(jPanel2Layout);
                          jPanel2Layout.setHorizontalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 859, Short.MAX_VALUE)
                          );
                          jPanel2Layout.setVerticalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 473, Short.MAX_VALUE)
                          );

                          jTabbedPane1.addTab("Financeiro", jPanel2);

                          javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                          jPanel9.setLayout(jPanel9Layout);
                          jPanel9Layout.setHorizontalGroup(
                                       jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 857, Short.MAX_VALUE)
                          );
                          jPanel9Layout.setVerticalGroup(
                                       jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 448, Short.MAX_VALUE)
                          );

                          jTabbedPane3.addTab("Clientes", jPanel9);

                          jLabel15.setText("Buscar");

                          chxNome.setSelected(true);
                          chxNome.setText("Endereco");

                          chxNome1.setSelected(true);
                          chxNome1.setText("Nome");

                          chxNome2.setSelected(true);
                          chxNome2.setText("Telefone");

                          chxNome3.setSelected(true);
                          chxNome3.setText("CNPJ");

                          chxNome4.setSelected(true);
                          chxNome4.setText("E-mail");

                          jButton5.setText("Buscar");

                          jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                       new Object [][] {
                                                    {null, null, null, null},
                                                    {null, null, null, null},
                                                    {null, null, null, null},
                                                    {null, null, null, null}
                                       },
                                       new String [] {
                                                    "Title 1", "Title 2", "Title 3", "Title 4"
                                       }
                          ));
                          jScrollPane2.setViewportView(jTable1);

                          btnImprimirRelatorio.setText("Imprimir relatorio");

                          jButton6.setText("Cancelar");

                          javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                          jPanel10.setLayout(jPanel10Layout);
                          jPanel10Layout.setHorizontalGroup(
                                       jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel10Layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                 .addGroup(jPanel10Layout.createSequentialGroup()
                                                                              .addComponent(jButton6)
                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                              .addComponent(btnImprimirRelatorio))
                                                                 .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                              .addComponent(jScrollPane2)
                                                                              .addGroup(jPanel10Layout.createSequentialGroup()
                                                                                           .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                           .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                     .addComponent(jButton5))
                                                                                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                                                                                     .addComponent(chxNome1)
                                                                                                                     .addGap(18, 18, 18)
                                                                                                                     .addComponent(chxNome)
                                                                                                                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                     .addComponent(chxNome2)
                                                                                                                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                     .addComponent(chxNome3)
                                                                                                                     .addGap(18, 18, 18)
                                                                                                                     .addComponent(chxNome4))))))
                                                    .addContainerGap(242, Short.MAX_VALUE))
                          );
                          jPanel10Layout.setVerticalGroup(
                                       jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel10Layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(chxNome)
                                                                 .addComponent(chxNome2)
                                                                 .addComponent(chxNome3)
                                                                 .addComponent(chxNome4)
                                                                 .addComponent(chxNome1))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(jLabel15)
                                                                 .addComponent(jButton5))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(btnImprimirRelatorio)
                                                                 .addComponent(jButton6))
                                                    .addContainerGap(34, Short.MAX_VALUE))
                          );

                          jTabbedPane3.addTab("Usuarios", jPanel10);

                          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                          jPanel3.setLayout(jPanel3Layout);
                          jPanel3Layout.setHorizontalGroup(
                                       jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane3)
                          );
                          jPanel3Layout.setVerticalGroup(
                                       jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane3)
                          );

                          jTabbedPane1.addTab("Relatorio", jPanel3);

                          javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                          jPanel4.setLayout(jPanel4Layout);
                          jPanel4Layout.setHorizontalGroup(
                                       jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 859, Short.MAX_VALUE)
                          );
                          jPanel4Layout.setVerticalGroup(
                                       jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGap(0, 473, Short.MAX_VALUE)
                          );

                          jTabbedPane1.addTab("Reclamação", jPanel4);

                          dktPrincipal.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

                          javax.swing.GroupLayout dktPrincipalLayout = new javax.swing.GroupLayout(dktPrincipal);
                          dktPrincipal.setLayout(dktPrincipalLayout);
                          dktPrincipalLayout.setHorizontalGroup(
                                       dktPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane1)
                          );
                          dktPrincipalLayout.setVerticalGroup(
                                       dktPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(jTabbedPane1)
                          );

                          jMenu1.setText("Arquivo");
                          jMenuBar1.add(jMenu1);

                          jMenu2.setText("Relatorios");

                          jMenu3.setText("Emitir relatorio de cadastros");

                          jMenuItem1.setText("Clientes");
                          jMenu3.add(jMenuItem1);

                          jMenuItem2.setText("Financeiro");
                          jMenu3.add(jMenuItem2);

                          jMenuItem3.setText("Reclamacoes");
                          jMenu3.add(jMenuItem3);

                          jMenu2.add(jMenu3);

                          jMenu4.setText("Emitir relatorio do sistema");

                          jMenuItem4.setText("Usuarios");
                          jMenu4.add(jMenuItem4);

                          jMenuItem5.setText("Empresa");
                          jMenu4.add(jMenuItem5);

                          jMenu2.add(jMenu4);

                          jMenuBar1.add(jMenu2);

                          jMenu5.setText("Usuario");
                          jMenuBar1.add(jMenu5);

                          setJMenuBar(jMenuBar1);

                          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                          getContentPane().setLayout(layout);
                          layout.setHorizontalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(dktPrincipal)
                          );
                          layout.setVerticalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(dktPrincipal)
                          );

                          pack();
             }// </editor-fold>//GEN-END:initComponents

             private void carregarTabela(String valor){
                          String sql = "from Fornecedor";
                          
                          if (valor != null) {
                                       sql += " where nome_fantasia like '%"+valor+"%'";
                          }
                          try {
                                       Session s = DAOSistema.getSessionFactory().getCurrentSession();
                                       s.beginTransaction();
                                       Query q  = s.createQuery(sql);
                                       List lForm = q.list();
                                       Iterator i = lForm.iterator();
                                       
                                       dtm.setNumRows(0);
                                       
                                       Fornecedor f;
                                       while (i.hasNext()) {
                                                    f = (Fornecedor) i.next();
                                                    dtm.addRow(f.getFornecedor());
                                       }
                                       s.getTransaction().commit();
                          } catch (Exception e) {
                                       e.printStackTrace();
                          }
             }
             
             private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
                          Fornecedor f = new Fornecedor(txtNomeFantasia.getText(), txtRazaoSocial.getText(), txtInscricaoEstadual.getText(), txtCnpj.getText(), txtTelefone.getText()
                                  , txtEmail.getText(), txtCep.getText(), txtLogradouro.getText(), txtBairro.getText(), Integer.parseInt(txtNumeroCasa.getText()), cbxUf.getSelectedItem().toString(), cbxCidade.getSelectedItem().toString(), cbxParceiro.getSelectedItem().toString());
                           try {
                                       Session s = DAOSistema.getSessionFactory().getCurrentSession();
                                       s.beginTransaction();
                                       s.save(f);
                                       s.getTransaction().commit();
                          } catch (Exception e) {
                                       e.printStackTrace();
                          }
             }//GEN-LAST:event_btnSalvarActionPerformed

             private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
                          if (txtBuscaClientes.getText() != " ") {
                                       carregarTabela(txtBuscaClientes.getText());
                          }else{
                                       JOptionPane.showMessageDialog(null, "Insiria um valor para procurar");
                          }
             }//GEN-LAST:event_btnBuscarClientesActionPerformed

             private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
                          int linha = tblFornecedores.getSelectedRow();
                          
                          if (linha <0) {
                                       JOptionPane.showMessageDialog(null, "Selecione pelo menos um cadastro");
                          }
                          else{
                                       id = Integer.valueOf(dtm.getValueAt(linha, 0).toString());
                                       String nome = dtm.getValueAt(linha, 1).toString();
                                       String razao = dtm.getValueAt(linha, 2).toString();
                                       String cidade = dtm.getValueAt(linha, 3).toString();
                                       String uf = dtm.getValueAt(linha, 4).toString();

                                       txtNomeFantasia.setText(nome);
                                       txtRazaoSocial.setText(razao);
                                       txtCidade.setText(cidade);
                                       cbxUf.setSelectedItem(uf);
                                       if (!txtNomeFantasia.isEnabled()) {
                                                    //habilitarDesabilitarComponentes();
                                       }
                                       tpnCadastro.setSelectedIndex(0);
                          }
             }//GEN-LAST:event_btnEditarClienteActionPerformed

             private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
                          // TODO add your handling code here:
             }//GEN-LAST:event_btnEditarActionPerformed

             /**
              * @param args the command line arguments
              */
             
             // Variables declaration - do not modify//GEN-BEGIN:variables
             private javax.swing.JButton btnBuscaCep;
             private javax.swing.JButton btnBuscarClientes;
             private javax.swing.JButton btnCancel;
             private javax.swing.JButton btnCancelar;
             private javax.swing.JButton btnEditar;
             private javax.swing.JButton btnEditarCliente;
             private javax.swing.JButton btnExcluirCliente;
             private javax.swing.JButton btnImprimirRelatorio;
             private javax.swing.JButton btnNovo;
             private javax.swing.JButton btnSalvar;
             private javax.swing.ButtonGroup buttonGroup1;
             private javax.swing.JComboBox<String> cbxCidade;
             private javax.swing.JComboBox<String> cbxMenorMaior;
             private javax.swing.JComboBox<String> cbxOrdenNome;
             private javax.swing.JComboBox<String> cbxParceiro;
             private javax.swing.JComboBox<String> cbxUf;
             private javax.swing.JCheckBox chbEmail;
             private javax.swing.JCheckBox chbEndereco;
             private javax.swing.JCheckBox chbId;
             private javax.swing.JCheckBox chbNome;
             private javax.swing.JCheckBox chbParceiro;
             private javax.swing.JCheckBox chbTelefone;
             private javax.swing.JCheckBox chbUsuario;
             private javax.swing.JCheckBox chxNome;
             private javax.swing.JCheckBox chxNome1;
             private javax.swing.JCheckBox chxNome2;
             private javax.swing.JCheckBox chxNome3;
             private javax.swing.JCheckBox chxNome4;
             private javax.swing.JDesktopPane dktPrincipal;
             private javax.swing.JButton jButton5;
             private javax.swing.JButton jButton6;
             private javax.swing.JLabel jLabel1;
             private javax.swing.JLabel jLabel10;
             private javax.swing.JLabel jLabel11;
             private javax.swing.JLabel jLabel12;
             private javax.swing.JLabel jLabel13;
             private javax.swing.JLabel jLabel14;
             private javax.swing.JLabel jLabel15;
             private javax.swing.JLabel jLabel16;
             private javax.swing.JLabel jLabel17;
             private javax.swing.JLabel jLabel2;
             private javax.swing.JLabel jLabel3;
             private javax.swing.JLabel jLabel4;
             private javax.swing.JLabel jLabel5;
             private javax.swing.JLabel jLabel6;
             private javax.swing.JLabel jLabel7;
             private javax.swing.JLabel jLabel8;
             private javax.swing.JLabel jLabel9;
             private javax.swing.JMenu jMenu1;
             private javax.swing.JMenu jMenu2;
             private javax.swing.JMenu jMenu3;
             private javax.swing.JMenu jMenu4;
             private javax.swing.JMenu jMenu5;
             private javax.swing.JMenuBar jMenuBar1;
             private javax.swing.JMenuItem jMenuItem1;
             private javax.swing.JMenuItem jMenuItem2;
             private javax.swing.JMenuItem jMenuItem3;
             private javax.swing.JMenuItem jMenuItem4;
             private javax.swing.JMenuItem jMenuItem5;
             private javax.swing.JPanel jPanel1;
             private javax.swing.JPanel jPanel10;
             private javax.swing.JPanel jPanel11;
             private javax.swing.JPanel jPanel12;
             private javax.swing.JPanel jPanel2;
             private javax.swing.JPanel jPanel3;
             private javax.swing.JPanel jPanel4;
             private javax.swing.JPanel jPanel5;
             private javax.swing.JPanel jPanel6;
             private javax.swing.JPanel jPanel7;
             private javax.swing.JPanel jPanel8;
             private javax.swing.JPanel jPanel9;
             private javax.swing.JScrollPane jScrollPane1;
             private javax.swing.JScrollPane jScrollPane2;
             private javax.swing.JScrollPane jScrollPane3;
             private javax.swing.JTabbedPane jTabbedPane1;
             private javax.swing.JTabbedPane jTabbedPane2;
             private javax.swing.JTabbedPane jTabbedPane3;
             private javax.swing.JTable jTable1;
             private javax.swing.JTable jTable2;
             private javax.swing.JTextField jTextField1;
             private javax.swing.JLabel lblTotalDeClientes;
             private javax.swing.JTable tblFornecedores;
             private javax.swing.JTabbedPane tpnCadastro;
             private javax.swing.JTextField txtBairro;
             private javax.swing.JTextField txtBuscaClientes;
             private javax.swing.JFormattedTextField txtCep;
             private javax.swing.JFormattedTextField txtCnpj;
             private javax.swing.JTextField txtEmail;
             private javax.swing.JFormattedTextField txtInscricaoEstadual;
             private javax.swing.JTextField txtLogradouro;
             private javax.swing.JTextField txtNomeFantasia;
             private javax.swing.JTextField txtNumeroCasa;
             private javax.swing.JTextField txtRazaoSocial;
             private javax.swing.JFormattedTextField txtTelefone;
             // End of variables declaration//GEN-END:variables
}
