/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAOSistema;
import controler.UsuarioSistema;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author tiago
 */
public class FormLogin extends javax.swing.JFrame {

             /**
              * Creates new form FormLogin
              */
             public FormLogin() {
                          initComponents();
             }

             /**
              * This method is called from within the constructor to initialize
              * the form. WARNING: Do NOT modify this code. The content of this
              * method is always regenerated by the Form Editor.
              */
             @SuppressWarnings("unchecked")
             // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
             private void initComponents() {

                          jLabel1 = new javax.swing.JLabel();
                          jLabel2 = new javax.swing.JLabel();
                          txtUsuario = new javax.swing.JTextField();
                          txtSenha = new javax.swing.JPasswordField();
                          btnLogar = new javax.swing.JButton();
                          btnSair = new javax.swing.JButton();
                          jLabel3 = new javax.swing.JLabel();

                          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                          jLabel1.setText("Usuario:");

                          jLabel2.setText("Senha:");

                          btnLogar.setText("Logar");
                          btnLogar.addActionListener(new java.awt.event.ActionListener() {
                                       public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                    btnLogarActionPerformed(evt);
                                       }
                          });

                          btnSair.setText("Sair");

                          jLabel3.setText("Bem vindo");

                          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                          getContentPane().setLayout(layout);
                          layout.setHorizontalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(layout.createSequentialGroup()
                                                                              .addContainerGap()
                                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                           .addComponent(jLabel1)
                                                                                           .addComponent(jLabel2)
                                                                                           .addComponent(txtUsuario)
                                                                                           .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                                                                           .addGroup(layout.createSequentialGroup()
                                                                                                        .addGap(58, 58, 58)
                                                                                                        .addComponent(btnLogar)
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                        .addComponent(btnSair))))
                                                                 .addGroup(layout.createSequentialGroup()
                                                                              .addGap(100, 100, 100)
                                                                              .addComponent(jLabel3)))
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                          );
                          layout.setVerticalGroup(
                                       layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                                    .addGap(35, 35, 35)
                                                    .addComponent(jLabel3)
                                                    .addGap(46, 46, 46)
                                                    .addComponent(jLabel1)
                                                    .addGap(9, 9, 9)
                                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                 .addComponent(btnLogar)
                                                                 .addComponent(btnSair))
                                                    .addContainerGap(81, Short.MAX_VALUE))
                          );

                          pack();
             }// </editor-fold>//GEN-END:initComponents

             
             
            
             
             private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
                          UsuarioSistema usuarioSistema = new UsuarioSistema();
                          String usuario = txtUsuario.getText();
                          String senha = txtSenha.getPassword().toString();
                          
                          if(txtUsuario.getText().equals("") || txtSenha.getPassword().equals("")){
                                       JOptionPane.showMessageDialog(null, "preencha todos os campos");
                          }
                          else{
                                       try{
                                                    
                                                    String sql = "select u.login, u.senha from usuarioSistema u where u.login like'"+txtUsuario.getText()+"' and u.senha like '"+txtSenha.getText()+"'";
                                                    Session s = DAOSistema.getSessionFactory().getCurrentSession();
                                                    s.beginTransaction();
                                                    Query q  = s.createQuery(sql);
                                                    System.out.println(sql);
                                                    q.setParameter(0, usuario);
                                                    q.setParameter(1, senha);
                                                    q.setMaxResults(1);
                                                                 FormMDI frmMDI = new FormMDI();
                                                                 frmMDI.setVisible(true);
                                                    
                                                    }
                                       
                                       catch(Exception e){
                                                    e.printStackTrace();
                                       }
                          }
             }//GEN-LAST:event_btnLogarActionPerformed

             /**
              * @param args the command line arguments
              */
             

             // Variables declaration - do not modify//GEN-BEGIN:variables
             private javax.swing.JButton btnLogar;
             private javax.swing.JButton btnSair;
             private javax.swing.JLabel jLabel1;
             private javax.swing.JLabel jLabel2;
             private javax.swing.JLabel jLabel3;
             private javax.swing.JPasswordField txtSenha;
             private javax.swing.JTextField txtUsuario;
             // End of variables declaration//GEN-END:variables
}
